apiVersion: kargo.akuity.io/v1alpha1
kind: Stage 
metadata:
  name: dev 
  namespace: workflow
  annotations:
    kargo.akuity.io/color: green
spec: 
  requestedFreight:
  - origin: 
      kind: Warehouse
      name: workflow
    sources: 
      direct: true
  promotionTemplate:
    spec: 
      steps:
        - task:
            name: promote

--- 
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage 
metadata:
  name: staging 
  namespace: workflow
  annotations:
    kargo.akuity.io/color: red
spec: 
  requestedFreight:
  - origin: 
      kind: Warehouse
      name: workflow
    sources: 
      direct: true
  promotionTemplate:
    spec: 
      steps:
        - task:
            name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage 
metadata:
  name: prod 
  namespace: workflow
  annotations:
    kargo.akuity.io/color: yellow
spec: 
  requestedFreight:
  - origin: 
      kind: Warehouse
      name: workflow
    sources: 
      direct: true
  promotionTemplate:
    spec: 
      steps:
        - task:
            name: promote
