apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: workflow
  namespace: workflow
spec:
  subscriptions:
  - image:
      repoURL: http://192.168.86.113:80/joiller-image-library/alqo
      # imagePath: joiller-image-library/alqo
      # credentials:
      #   secretRef:
      #     name: harbor-creds
      #     usernameKey: username
      #     passwordKey: password
      # insecure: true
      watchInterval: 1m
      imageSelectionStrategy: SemVer
  - git:
      repoURL: https://github.com/the-one-rvs/server-setup
      branch: main
    # credentials:
    #   secretRef:
    #     name: git-creds
    #     usernameKey: username
    #     passwordKey: password