apiVersion: v1
kind: Service
metadata:
  name: alqo-service-new
  namespace: default
spec:
  type: NodePort
  selector:
    app: alqo-new
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30009