apiVersion: v1
kind: Service
metadata:
  name: alqo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: elevate
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30007